server:
  port: 8081

spring:
  application:
    name: glcoud-aipan
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://14.103.227.76:3306/dcloud_aipan?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Gkd03073436
  #redis配置
  data:
    redis:
      host: 14.103.227.76
      port: 6379
      password: $RFV6tfc

# mybatis-plus配置
mybatis-plus:
  global-config:
    #逻辑删除配置
    db-config:
      logic-delete-field: del # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
  configuration:
    # 日志输出配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启驼峰命名转换

# minio配置
minio:
  endpoint: http://14.103.227.76:9000
  access-key: minio_gaokd
  access-secret: minio_gaokd123
  bucket-name: ai-pan
  avatar-bucket-name: avatar